#ifndef ERROR_H
#define ERROR_H

#include <QString>

//error messages
const QString ERROR_INVALID_FILE = QString("ERROR_INVALID_FILE");
const QString ERROR_SYSTEM_FAULT = QString("ERROR_SYSTEM_FAULT");
const QString ERROR_INVALID_CHARACTERS = QString("ERROR_INVALID_CHARACTER");
const QString ERROR_INVALID_FILE_EXTENSION = QString("ERROR_INVALID_FILE_EXTENSION");
const QString ERROR_FILE_NOT_FOUND = QString("ERROR_FILE_NOT_FOUND");
const QString ERROR_NO_FILE_NAME_SPECIFIED = QString("ERROR_NO_FILE_NAME_SPECIFIED");
const QString ERROR_PAYLOAD_NOT_FOUND = QString("ERROR_PAYLOAD_NOT_FOUND");

//pe file error messages
const QString ERROR_INVALID_EXECUTABLE = QString("ERROR_INVALID_EXECUTABLE");
const QString ERROR_INVALID_DOS_SIGNATURE = QString("ERROR_INVALID_DOS_SIGNATURE");
const QString ERROR_INVALID_PE_SIGNATURE = QString("ERROR_INVALID_PE_SIGNATURE");
const QString ERROR_UNABLE_TO_MORPH_EXECUTABLE = QString("ERROR_UNABLE_TO_MORPH_EXECUTABLE");
const QString ERROR_NO_MATCHING_SECTION_HEADER_NAME = QString("ERROR_NO_MATCHING_SECTION_HEADER_NAME");

//keystone error messages
const QString ERROR_OPENING_KEYSTONE = QString("ERROR_OPENING_KEYSTONE");
const QString ERROR_ASSEMBLY_FAILED_KEYSTONE = QString("ERROR_ASSEMBLY_FAILED_KEYSTONE");

//success messages
const QString SUCCESS_VALID_EXECUTABLE = QString("SUCCESS_VALID_EXECUTABLE");
const QString SUCCESS_MORPHED_EXECUTABLE = QString("SUCCESS_MORPHED_EXECUTABLE");
const QString SUCCESS_MATCHING_SECTION_HEADER_NAME = QString("SUCCESS_MATCHING_SECTION_HEADER_NAME");

//keystone success messages
const QString SUCCESS_ASSEMBLY_TO_MACHINE_CODE_KEYSTONE = QString("SUCCESS_ASSEMBLY_TO_MACHINE_CODE_KEYSTONE");

#endif // ERROR_H
