#ifndef ERROR_H
#define ERROR_H

#include <QString>

const QString ERROR_INVALID_FILE = QString("ERROR_INVALID_FILE");
const QString ERROR_SYSTEM_FAULT = QString("ERROR_SYSTEM_FAULT");
const QString ERROR_INVALID_CHARACTERS = QString("ERROR_INVALID_CHARACTER");
const QString ERROR_INVALID_FILE_EXTENSION = QString("ERROR_INVALID_FILE_EXTENSION");
const QString ERROR_FILE_NOT_FOUND = QString("ERROR_FILE_NOT_FOUND");

#endif // ERROR_H
